### ISSUE TITLE
CI での `biome check` が `lint` / `fmt` タスクとは別のものを指摘してくる。

### ISSUE THREAD

**Issue by Jxck** [Jxck/mozaic.fm#16]
@hiroppy 

- ローカルは `biome format` と `biome lint` の script が package.json にある
- CI では `npx biome check .` が流れてる
  - https://github.com/Jxck/mozaic.fm/blob/main/.github/workflows/ci.yml#L25
- ローカルで両方チェックしてるのに push すると CI で落ちる
  - https://github.com/Jxck/mozaic.fm/actions/runs/8649699744/job/23716550057#step:4:37
- `check --apply` でおなした
  - https://github.com/Jxck/mozaic.fm/pull/14/commits/5eb732304970f5f60623c19c129c97b09dc826e8
- ローカルでも `check` を使うか CI でも `lint` を使うかしたほうが良さそう?

**Comment by hiroppy** [comment]
biome再導入時に同じスクリプトに統一しちゃいます！
