### ISSUE TITLE
Biome 導入

### ISSUE THREAD

**Issue by Jxck** [Jxck/mozaic.fm#20]
#18 に伴う修正

**Comment by hiroppy** [comment]
biomeのlintを有効にするかどうか？

結論: biomeのlintとeslintの両方を利用する
理由: biomeのlintを利用することにより、速度と3rdの依存を減らし、next.jsのlintのみeslintに移譲させるため

biome lint:
  - pros
    - 3rdのプラグインに依存しなくていい
    - 速い
  - cons
    - カスタマイズができない
    - next.jsの対応がない
eslint:
  - pros
    - 様々なプラグインで幅広くサポートできる
  - cons
    - 遅い
    - アップデートの追従がプラグインに依存される可能性がある
