### ISSUE TITLE
コンテンツの扱いについて

### ISSUE THREAD

**Issue by hiroppy** [Jxck/mozaic.fm#25]
以下の方法がある。前提として、markdownをどこに置きたいかに焦点を当てたい。

### app router無い定義

[Next.js公式の方法](https://nextjs.org/docs/app/building-your-application/configuring/mdx)で、`episodes/0/xxxx/page.md`みたいな感じでページのように定義する。

参考: https://www.alexchantastic.com/building-a-blog-with-next-and-mdx

**markdownは、ページとして扱うためapp以下に入る**

#### Pros

- 公式サポート
- 表示するだけならそんなに複雑じゃない

#### Cons

- 一覧の取得は、fsを利用し`.next`から外すので、appと横のレイヤーに書く必要がある
- 一覧を展開するときに、ファイル名しかわからないのでfontmatter等の取得で内部を見るためパフォーマンスに問題が出る可能性がある
  - e.g 一覧ページでタイトルとかを知りたいとき
  - ただ静的に作成してしまうので影響範囲はdevとビルドのみ

### contentlayerを利用する

[contentlayer](https://contentlayer.dev/)を利用し、Astroみたいにappの横に`content`ディレクトリを作成しそこにいれる。Astroのcontent collectionとやり方は同様。

**markdownは、ページとして扱わないため指定したディレクトリに入る**

#### Pros

- frontmatterの型が定義できる
- tsで扱える

#### Cons

- 3rd
- 設定を書く必要があるので、複雑性が増す

### 自前でcontent collectionを実装する

参考: https://qiita.com/cieloazul310/items/55e8d13e29d98425e2f8

**markdownは、ページとして扱わないため指定したディレクトリに入る**

#### Pros

- ライブラリの依存度を減らせる

#### Cons

- 結構コードを書く量が増えそう
- 機能追加するたびにコードを書く必要がある

@Jxck どれが今後、扱いやすいか意見もらえますか？

**Comment by Jxck** [comment]
今後剥がすことも考えると
- ディレクトリ構造
- URL
は極力維持したいけど、それ以外はあまりこだわりない。
なので、 Next 標準でできるならそれがいいかな？
