### ISSUE TITLE
Hono - Cloudflare

### ISSUE THREAD

**Issue by Jxck** [Jxck/mozaic.fm#4]
- [] サーバを Honoxで作る
- [] Cloudflare Pages にデプロイできる

**Comment by Jxck** [comment]
cloudflare が dev week で、なんか新しい話出そうだから、それを見届けてから環境作る。

**Comment by Jxck** [comment]
# 調査

## Cloudflare

- cloudflare worker は単一の worker 専用
- assets がある場合は cloudflare pages
- 今回は pages を使う

## Hono

- Hono はサーバサイドのフレームワーク
  -  JSX は使えるがテンプレート
  - router も自前
  - ほぼ Express
- Honox は fullstack
  - file base routing
  - island architecture
  - まだ途上だけど薄いから大きくは壊れなさそう

## 選定

- Honox で作って Pages にデプロイする

**Comment by Jxck** [comment]
Honox - Cloudflare Pages の調査はだいたいできた。
試しにあげてみたもの。

https://mozaic-v2.pages.dev/

**Comment by Jxck** [comment]
@hiroppy @sakit0 Honox はデフォルトのルートディレクトリが `/app` で、そこにあるファイル名をベースに動いてるっぽい。
オプションめっちゃ頑張れば `/app` を `/src` に変えることもできるっぽいけど、多分色々ハマるので、できれば今のうちに `/src` を `/app` に変えたいんだけど、他でなんかまずいところある？

**Comment by hiroppy** [comment]
@hiroppy 大丈夫です。もし、nextjsと似たような感じにしたい場合は `src/app` にしたいぐらいですかね。。

**Comment by Jxck** [comment]
@hiroppy それもちょっと考えたんだけど

https://github.com/honojs/honox?tab=readme-ov-file#project-structure-1

```
.
├── app
│   ├── client.ts // client entry file
│   ├── global.d.ts
│   ├── islands
│   │   └── counter.tsx // island component
│   ├── routes
│   │   ├── _renderer.tsx
│   │   └── index.tsx
│   └── server.ts
├── package.json
├── tsconfig.json
└── vite.config.ts
```

設定ファイル系含めてこの構造が前提になってるところが結構多いっぽいんだよね。

https://github.com/honojs/honox/blob/main/src/server/with-defaults.ts

なので `src/app/` だとなんか色々重複しそうな気もしてる。
あと、無駄な一階層になりそうな気もする。

だから、今のうちに `src/` -> `app/` が無難そうかなぁと言う気がする。
まだ枯れてないフレームワークだから、変にレール外れると無駄な苦労しそうだから、特に `src/` じゃないとだめな連携がなければ、変えちゃいたいかな。

**Comment by hiroppy** [comment]
なるほどー、では`/app`で大丈夫です！

**Comment by Jxck** [comment]
Honox をここにマージしてるんだが、どうしても以下のモジュールがみつからないと言われる。

```ts
import adapter from "@hono/vite-dev-server/cloudflare";
```

よくわからんけど、 pnpm じゃなくて npm でやったら上手くいった。

1. vite-dev-server 側を直せないか見にいく
2. 最悪

**Comment by Jxck** [comment]
pnpm でもできた。
依存を明示的に入れるだけだった。本家も PR した。
https://github.com/honojs/starter/pull/32
