### ISSUE TITLE
Hack-a-thon

### ISSUE THREAD

**Issue by Jxck** [Jxck/mozaic.fm#43]
# やったこと

- storybook
- chromatic 途中
- token studio 契約
  -  移行は途中
- markdown のパースが途中
- RSS 実装中 

# ADR

- Cloudflare へのデプロイは、サイズが大きくなりすぎたためやめることに
  - 自分でサーバにデプロイする
  - Docker にする

**Comment by hiroppy** [comment]
TODO

- algoliaを辞める
  - pagefindを入れる
- rssを実装

**Comment by Jxck** [comment]
#49 に移動
