### ISSUE TITLE
CI 環境

### ISSUE THREAD

**Issue by Jxck** [Jxck/mozaic.fm#5]
- [ ] 単体テスト Vitest
- [ ] Chromatic のテスト
- [ ] Cloudflare へのデプロイ
- [ ] あたりが GA でできる

**Comment by Jxck** [comment]
cloudflare がなくなったので

- lint
- test
- chromatic
あたりができればいい

**Comment by hiroppy** [comment]
buildを追加 done

**Comment by Jxck** [comment]
たぶんできてる。
